### PR TITLE
[config] Added Github cloud schema

### PR DESCRIPTION
**Pull request by BenGallagher-RL**
to:
cc: @airbnb/streamalert-maintainers
related to:
resolves:

## Background

Github Cloud Enterprise allows for direct pushing of audit logs to an S3 bucket. The schema for these logs has many potential fields. By reviewing several weeks of Github logs in the S3 bucket, a schema has been developed to contain the multiple fields, and to determine if they are optional or not.

## Changes

* Add "ghe:cloud" schema to the ghe.json schema file.

## Testing

This schema has been in use without issue for several weeks.

### CODE REVIEW

**Review by chunyong-lin — COMMENTED** [review]
Hi @BenGallagher-RL Thank you for your contribution and this schema is very helpful for the community.

Can you add testing event(s) to this PR too? See the example in https://github.com/airbnb/streamalert/pull/1263. The testing event(s) will be in json format.

**Comment by BenGallagher-RL** [comment]
Let me know if there's anything else you would like me to add.

**Comment by BenGallagher-RL** [comment]
There's an error is this commit's config. Fixing imminently.

**Comment by BenGallagher-RL** [comment]
FIxed. Ready for review @chunyong-lin

**Pull request closed without merging**
