### PR TITLE
Hotfix/links and spelling

### PR DESCRIPTION
**Pull request by JUULShawn**
to: @ryandeivert 
cc: @airbnb/streamalert-maintainers

## Background

* Updates a broken link in the docs. 
* Includes a pass on spelling throughout, if we care about that.

## Changes

* Corrects a broken link to Athena Repair Table info at AWS
* Includes sundry spelling updates in code, tests, docs, and comments

## Testing

Verified that the updated link is correct and does work
Re-ran tests to confirm that they still pass: tests/scripts/unit_tests.sh

### CODE REVIEW

**Comment by JUULShawn** [comment]
Thanks Ryan, really cool project! I'm excited to work with it beyond spelling of course, over time. btw tt looks like I cannot merge the branch, I assume you guys will do this?

**Comment by JUULShawn** [comment]
Thanks Ryxias, cool project!

**Comment by ryandeivert** [comment]
yes @JUULShawn we will merge it when the time is right. thanks for the contribution!

**Comment by JUULShawn** [comment]
Will the changes be included with 2.3.0? I see that it was added to the milestone but then removed...

**Comment by ryandeivert** [comment]
@JUULShawn sorry, no, that shipped yesterday. we can get it in soon though

**Comment by JUULShawn** [comment]
Awesome! Congrats on shipping the update!

**Comment by ryandeivert** [comment]
this will be included with our `2.3.1` release

**Pull request merged**
