### PR TITLE
[lambda][output] adding `incident_key` for PD output to support de-duping

### PR DESCRIPTION
**Pull request by ryandeivert**
to @airbnb/streamalert-maintainers 

size: small
resolves: #58 

## changes ##
Super tiny change that adds an `incident_key` for pagerduty output to support de-duplication of incidents on the PD side. This `incident_key` will contain the triggering `rule_name`.

### CODE REVIEW

**Comment by mime-frame** [comment]
@ryandeivert - can you include testing steps going forward in your PR description?

**Comment by mime-frame** [comment]
@ryandeivert - what happens if there is a rule name that is the same for diff clusters/rules files?

**Comment by ryandeivert** [comment]
@mimeframe great point and question. Working on a way to determine that now.

**Comment by ryandeivert** [comment]
@jacknagz merged in master to resolve conflicts. PTAL and approve.

**Pull request merged**
