### PR TITLE
 getting started minor update

### PR DESCRIPTION
**Pull request by securityclippy**
to: @airbnb/streamalert-maintainers
cc: <optional-cc-to-specific-users>
size: small|medium|large
resolves #<related-issue-goes-here>

## Background

Just a small documentation update

## Changes

* how to solve psutil installation problems with python-dev
* ...

## Testing

Steps for how this change was tested and verified

### CODE REVIEW

**Comment by ryandeivert** [comment]
hey @securityclippy I looked in the slack to try to see if you mentioned the problem you experienced with `psutil` but came up short. Do you have steps to reproduce the problem you had?

**Comment by securityclippy** [comment]
@ryandeivert sure.  Any fresh install of ubuntu 16.04 should produce the issue.  I'm sure there are probably others as well, but basically all you need to do is follow the ```getting started``` through to the ```pip install -r  requirements.txt```.  During the requirements installation,  the wheel build for psutil will fail.  The above  listed fix will get your past that  point and able to continue on.

**Comment by securityclippy** [comment]
PS.  I added the ```virtualenv -p python2.7 venv``` too here, apparently, because I'm bad at breaking up issues.  That was just a clarification for explicit use of python2.7 rather than implicit, as some distro's are starting to ship with python3 as the default.

**Comment by jacknagz** [comment]
@securityclippy Thanks for the change, can you rebase this branch off latest master?

**Comment by ryandeivert** [comment]
@securityclippy thanks for the clarification! I also support the addition of `-p python2.7` 👍

**Comment by securityclippy** [comment]
@jacknagz @ryandeivert ack, rebase incoming shortly

**Pull request merged**
