### PR TITLE
[streamalert][bug] Fix to allow nested structured data and normalization

### PR DESCRIPTION
**Pull request by javuto**
to @ryandeivert 
cc @mime-frame 

This code fixes the problem of having nested data in normalized fields and not be detected by the rules as datatype. Resolves: https://github.com/airbnb/streamalert/issues/333

## Change

The method `match_types` now sets the value of `record['normalized_types']` instead of returning it. Given that the method was being invoked recursively, the impacted field was not updated correctly and the nested normalized fields that we were interested on, they were not set. With this fix the existing rules work as expected while other new rules can be implemented and the normalization can be used with nested fields.

## Testing

Tested for existing rules using `python manage.py lambda test --processor all`
Added coverage for this in the existing test `tests/unit/stream_alert_rule_processor/test_rules_engine.py` and checked with the following command:
```
$ ./tests/scripts/unit_tests.sh
...
Rules Engine - Match normalized types against record ... ok
Rules Engine - Recursively walk though all nested keys and update ... ok
...
```

### CODE REVIEW

**Comment by mime-frame** [comment]
Update your PR description with a Testing section with how you tested your changes @javuto :)

**Comment by mime-frame** [comment]
Awesome, thanks @javuto ! @ryandeivert - you're up :)

**Comment by ryandeivert** [comment]
@javuto please add the line `resolves: #333` below the to & cc lines so the issue will be closed when this PR is merged

**Comment by javuto** [comment]
@chunyong-lin is taking care of this

**Pull request closed without merging**
