### PR TITLE
[app] increase app default request timeout

### PR DESCRIPTION
**Pull request by chunyong-lin**
to: @austinbyers 
cc: @airbnb/streamalert-maintainers
size: small
resolves N/A

## Background
Increase app default request timeout to 5 seconds.

## Testing
Deployed in internally, and all Apps are working correctly.

### CODE REVIEW

**Comment by austinbyers** [comment]
Can you provide any context for why 5 is better?

**Comment by chunyong-lin** [comment]
During internal deploy of Slack Apps, the default timeout 3.05s causes connection to `https://slack.com/api/` to timeout. Simply increase the default timeout to 5s fixing the issue.

**Comment by ryandeivert** [comment]
hey @chunyong-lin thanks for adding this! since this mostly seems to impacting Slack, can we just override the `_DEFAULT_REQUEST_TIMEOUT` class constant in the `SlackApp` subclass?

**Comment by chunyong-lin** [comment]
Hey @ryandeivert Great suggestion! I made the change!
Per conversation with Ryan, it is better to overwrite the request timeout in app individually, rather than making change in the base app.

We will keep `3.05` seconds as default request timeout in base class `AppIntegration`. It is recommended to set the request timeout slightly larger than a multiple of 3 according to the doc [here](http://docs.python-requests.org/en/master/user/advanced/#timeouts).

**Pull request merged**
